# Generated by Django 4.0.3 on 2022-03-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This represents the sample name presentation.', max_length=48, verbose_name='Sample name')),
            ],
        ),
    ]
